// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCISBX6J3p9xNT9GO90FIP2GgP6Dx7GjVA',
    appId: '1:244432598647:web:eb1764b63f1ea5bf467872',
    messagingSenderId: '244432598647',
    projectId: 'tracker-app-56-6e384',
    authDomain: 'tracker-app-56-6e384.firebaseapp.com',
    storageBucket: 'tracker-app-56-6e384.appspot.com',
    measurementId: 'G-Z5XG8CH5VK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd6MMX940aoeibN-dZ2jb4qUvEYjqeHRc',
    appId: '1:244432598647:android:addae3f46c0bd532467872',
    messagingSenderId: '244432598647',
    projectId: 'tracker-app-56-6e384',
    storageBucket: 'tracker-app-56-6e384.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWHfXSqnJRmoPTrJ6SzC_yBmuxnluEJQs',
    appId: '1:244432598647:ios:c5da194fcaa42c41467872',
    messagingSenderId: '244432598647',
    projectId: 'tracker-app-56-6e384',
    storageBucket: 'tracker-app-56-6e384.appspot.com',
    iosBundleId: 'com.example.placetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWHfXSqnJRmoPTrJ6SzC_yBmuxnluEJQs',
    appId: '1:244432598647:ios:c5da194fcaa42c41467872',
    messagingSenderId: '244432598647',
    projectId: 'tracker-app-56-6e384',
    storageBucket: 'tracker-app-56-6e384.appspot.com',
    iosBundleId: 'com.example.placetracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCISBX6J3p9xNT9GO90FIP2GgP6Dx7GjVA',
    appId: '1:244432598647:web:07d80bbc6d5322cc467872',
    messagingSenderId: '244432598647',
    projectId: 'tracker-app-56-6e384',
    authDomain: 'tracker-app-56-6e384.firebaseapp.com',
    storageBucket: 'tracker-app-56-6e384.appspot.com',
    measurementId: 'G-6E6DRRPEBY',
  );
}
